name: Release

###
# ATTN MAINTAINERS
# ---
# Run this from root directory:
#   # example: node bin/version.js patch
#   $ node bin/version.js patch|minor|major
#   $ git push origin master --tags
###

on:
  push:
    tags:
      - "v**"
    branches-ignore:
      - "**"

jobs:
  release:
    name: Tauri (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: (setup) cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: (ubuntu) install webkit2gtk
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libgtksourceview-3.0-dev webkit2gtk-4.0 libappindicator3-dev

      - name: (setup) yarn
        run: npm install -g yarn

      - name: (client) install dependencies
        run: yarn install --frozen-lockfile --network-timeout=30000

      - name: Tauri Build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE_CODE_SIGNING: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        with:
          # NOTE: "__VERSION__" automatically replaced
          tagName: __VERSION__-tauri
          releaseName: __VERSION__
          body: "See the assets to download this version and install."
          prerelease: false
          draft: false
